/**
 * @fileoverview gRPC-Web generated client stub for app.protos
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: example.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as example_pb from './example_pb'; // proto import: "example.proto"


export class GreeterClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSayHello = new grpcWeb.MethodDescriptor(
    '/app.protos.Greeter/SayHello',
    grpcWeb.MethodType.UNARY,
    example_pb.HelloRequest,
    example_pb.HelloReply,
    (request: example_pb.HelloRequest) => {
      return request.serializeBinary();
    },
    example_pb.HelloReply.deserializeBinary
  );

  sayHello(
    request: example_pb.HelloRequest,
    metadata?: grpcWeb.Metadata | null): Promise<example_pb.HelloReply>;

  sayHello(
    request: example_pb.HelloRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: example_pb.HelloReply) => void): grpcWeb.ClientReadableStream<example_pb.HelloReply>;

  sayHello(
    request: example_pb.HelloRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: example_pb.HelloReply) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/app.protos.Greeter/SayHello',
        request,
        metadata || {},
        this.methodDescriptorSayHello,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/app.protos.Greeter/SayHello',
    request,
    metadata || {},
    this.methodDescriptorSayHello);
  }

}

